//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Leyva_Cars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodigoVerificacion
    {
        public int Id_Codigo { get; set; }
        public int Id_Usuario { get; set; }
        public string Codigo { get; set; }
        public string TipoVerificacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public System.DateTime FechaExpiracion { get; set; }
        public Nullable<bool> Usado { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
