//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Leyva_Cars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consultas()
        {
            this.Pedidos = new HashSet<Pedidos>();
        }
    
        public int Id { get; set; }
        public string NombreCliente { get; set; }
        public string TelefonoCliente { get; set; }
        public string MarcaVehiculo { get; set; }
        public string ModeloVehiculo { get; set; }
        public Nullable<int> AnioVehiculo { get; set; }
        public string RutaImagen { get; set; }
        public string NombresDetectadosIA { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public string TipoConsulta { get; set; }
        public string MensajeWhatsApp { get; set; }
        public string Estado { get; set; }
        public string RespuestaVendedor { get; set; }
        public Nullable<System.DateTime> FechaConsulta { get; set; }
        public Nullable<System.DateTime> FechaRespuesta { get; set; }
    
        public virtual Productos Productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos { get; set; }
    }
}
