//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Leyva_Cars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public int Id { get; set; }
        public Nullable<int> ConsultaId { get; set; }
        public string NombreCliente { get; set; }
        public string TelefonoCliente { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> PrecioAcordado { get; set; }
        public string Estado { get; set; }
        public string Notas { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual Consultas Consultas { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
