//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Leyva_Cars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto_Imagenes
    {
        public int Id_Imagen { get; set; }
        public int Id_Producto { get; set; }
        public string Imagen { get; set; }
        public int Orden { get; set; }
        public string Alt_Text { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
